---
# tasks file for mongodb
- include_vars: secrets.yml
- name: Install Mongodb
  apt:
    name: mongodb
    state: present
- name: Start and enable the engine
  service:
    name: mongodb
    state: started
    enabled: true
- name: Allow for outside connections
  lineinfile:
    path: /etc/mongodb.conf
    regexp: '?bind_ip = 127.0.0.1'
    line: 'bind_ip = 127.0.0.1'
  notify:
    - restart mongodb
- name: Install Pip
  apt:
    name: python-pip
    state: present
- name: Install Pymongo
  pip:
    name: pymongo
    state: present
- name: Check if the admin user is already created
  command: grep "^auth = true" /etc/mongodb.conf
  register: auth
  ignore_errors: yes

- name: Add administrator to db
  mongodb_user:
    database: admin
    name: root
    password: "{{ dbpass }}"
    roles: root
    state: present
  when: auth.rc == 1

- name: Enable auth
  lineinfile:
    path: /etc/mongodb.conf
    regexp: '#?auth \= true'
    line: 'auth = true'
  notify: restart mongodb